### ISSUE TITLE
Problema na saída de algumas células

### ISSUE THREAD

**Issue by Re-Tonolli** [Explora-FT/Curso-Python-Notebooks#4]
Célula 9, não há o retorno correto dos termos de 1 a 4 
https://github.com/Explora-FT/Curso-Python-Notebooks/blob/909557ea4294d9a98abcf926ec9967814ac935ab/02_Mais_tipos.ipynb#L301
Célula 13, não há o retorno correto dos termos de 2 em 2 
https://github.com/Explora-FT/Curso-Python-Notebooks/blob/909557ea4294d9a98abcf926ec9967814ac935ab/02_Mais_tipos.ipynb#L408
Células após 24 não possuem resposta pois apresentou o erro.
https://github.com/Explora-FT/Curso-Python-Notebooks/blob/909557ea4294d9a98abcf926ec9967814ac935ab/02_Mais_tipos.ipynb#L725

**Comment by Anakin86708** [comment]
Corrigido em: #5
